apiVersion: v1
kind: Secret
metadata:
  name: namespace-secret
  annotations:
    comment: "This is a secret that will be used to decrypt Age Secrets in k8s cluster"
stringData:
  secretKey: "AGE-SECRET-KEY-1WU6V2ZS76MU79G2427F7HD4HPXYQ48HTZG95N3P4XR22A7C4SH9SA6TMFY"
