[project]
name = "operator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "kopf>=1.37.4",
    "kubernetes>=32.0.1",
    "pyrage>=1.2.4",
]
